name: blackthorn_manor
description: Interactive Document Reader for Blackthorn Manor Investigation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Networking
  http: ^1.1.0
  
  # JSON Serialization
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  # UI Enhancements
  flutter_animate: ^4.3.0
  flutter_cube: ^0.1.1
  particles_flutter: ^0.1.4
  vibration: ^1.8.4
  
  # Charts and Analytics
  fl_chart: ^0.65.0
  
  # Utilities
  path_provider: ^2.1.1
  intl: ^0.18.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: Crimson
      fonts:
        - asset: assets/fonts/CrimsonPro-Regular.ttf
        - asset: assets/fonts/CrimsonPro-Bold.ttf
          weight: 700
    - family: Libre
      fonts:
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
        - asset: assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700